### ISSUE TITLE
Rails console and server fail to start in staging and production modes locally

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal_web_ui#395]
The Rails server fails to start locally in staging and production modes with an `undefined method 'health_check'` error:

```ruby
$ bioportal_web_ui git:(master) RAILS_ENV=production RAILS_SERVE_STATIC_FILES=true rails s

=> Booting Puma
=> Rails 7.0.8 application starting in production
=> Run `bin/rails server --help` for more startup options
Exiting
/Users/jlvendetti/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/newrelic_rpm-9.17.0/lib/new_relic/agent/configuration/yaml_source.rb:39:in `rescue in initialize': undefined method `health_check' for nil:NilClass (NoMethodError)
```

The same error occurs when trying to run the console in production mode, i.e., `rails c -e production`.

Attempting to start with the New Relic agent disabled also fails:

```console
$ bioportal_web_ui git:(master) NEW_RELIC_AGENT_ENABLED=false RAILS_ENV=production rails s

=> Booting Puma
=> Rails 7.0.8 application starting in production
=> Run `bin/rails server --help` for more startup options
Exiting
/Users/jlvendetti/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/newrelic_rpm-9.17.0/lib/new_relic/agent/configuration/yaml_source.rb:39:in `rescue in initialize': undefined method `health_check' for nil:NilClass (NoMethodError)
```

It appears that a `newrelic.yml` configuration file was introduced in pull request #336 where the code expects a New Relic license key and application name in the encrypted credentials files:

```yaml
license_key: <%= Rails.application.credentials[:newrelic][:license_key] %>

app_name: <%= Rails.application.credentials[:newrelic][:app_name] %>
```

The encrypted credentials files for staging and production (in /config/credentials) have no such entries. I tried looking at the main credentials file (/config/credentials.yml.enc), but there doesn't appear to be a `master.key` file anywhere that allows me to decrypt it -- even in our private `bioportal_config` repository.

```console
$ bioportal_web_ui git:(master) ✗ EDITOR="code --wait" bin/rails credentials:edit
Couldn't decrypt config/credentials.yml.enc. Perhaps you passed the wrong key?
```

**Comment by jvendetti** [comment]
I removed the global encrypted credentials file in June of '23 (https://github.com/ncbo/bioportal_web_ui/commit/d55d007381d510de38f1f22878eb14977f0c6251). I take it this is AgroPortal's file that came in mistakenly?
